In [1]:
import numpy as np

In [2]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [3]:
# find all non-zero elements in x
np.nonzero(x)

(array([1, 2, 3, 4, 5, 6], dtype=int32),)

In [4]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)


In [5]:
# calculate the following equations
# A + B
# A - B
# A * B (matrix product)
# A' (transpose of A)
A + B
A - B
np.dot(A, B)
np.transpose(A)


array([[-1.33020721, -0.16313613,  0.26592256, -0.09595558,  0.42881188],
       [ 0.31446431, -1.08988876, -1.60543007, -0.12891141,  0.10649074],
       [-1.32841942,  0.48881673,  0.64999529,  2.10865132,  0.07416669],
       [ 0.24216968,  0.01174628, -0.97778975,  0.15806943,  1.0797857 ],
       [ 0.25124825,  2.17994503, -1.27636269, -0.09581612, -0.52831314]])

In [6]:
# calculate the mean, sum, max, min value for each column in A
np.mean(A, axis = 0)
np.sum(A, axis = 0)
np.max(A, axis = 0)
np.min(A, axis = 0)


array([-1.33020721, -1.60543007, -1.32841942, -0.97778975, -1.27636269])

In [7]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)
A_min = np.min(A)
A_max = np.max(A)
for i in range(len(A)):
    for j in range(len(A)):
        A[i,j] = (A[i,j] - A_min) / (A_max - A_min)
A

array([[0.07270689, 0.50718736, 0.07317918, 0.48808895, 0.49048728],
       [0.38101744, 0.13619292, 0.55324684, 0.42721694, 1.        ],
       [0.49436386, 0.        , 0.59582612, 0.16580664, 0.08693125],
       [0.39876484, 0.39005875, 0.98116601, 0.4658718 , 0.39880168],
       [0.53739508, 0.45224602, 0.44370682, 0.70936583, 0.28454695]])

In [8]:
# advanced exercise
# solve the system of equations:
# 3 * x0 + x1 = 9
# x0 + 2 * x1 = 8

# Ax = b 
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
x

array([2., 3.])

In [9]:
# compare x with the product of inverse A and b
np.dot(np.linalg.inv(A), b) #x = (A^-1)(b)

array([2., 3.])